/** Domain types.
 *
 * THESE ARE PROVISIONAL AND THE PROJECT SHOULD NOT KEEP THEM. `npm run
 * api:types` generates `schema.gen.ts` from the API's own /openapi.json, which
 * cannot drift from the server; these exist so the app compiles before that
 * generation has been run against a live backend, and so a reviewer can see
 * the shape without starting one.
 *
 * CORRECTED 2026-09-11. This block previously said the types were kept honest
 * by `src/api/__tests__/schema.test.ts`, which fetches the live schema and
 * fails on a disagreement. THAT FILE HAS NEVER EXISTED. Nothing checks the
 * interfaces below against the server, and a described guard that is absent is
 * worse than an acknowledged gap, because it stops anyone looking. AUDIT 3.1
 * is the open item; `schema.gen.ts` is still not generated or committed.
 *
 * The urgency ordering below is the exception and IS generated -- see the note
 * on the re-export. */

/* The urgency ordering is NOT defined here any more. AUDIT 1.3 found it in
 * five independent copies across the repository, one of which was this file,
 * and a clinical sort key with five definitions has five places to be wrong.
 *
 * `urgency.gen.ts` is generated by backend/scripts/gen_frontend_constants.py
 * from `UrgencyLevel._URGENCY_PRIORITY`, the same mapping the server sorts the
 * queue with. Re-exported rather than merely imported so existing importers of
 * `./types` keep working and there is still exactly one definition.
 *
 * NOTE the rank base changed with this: the hand-written copy was 0-based and
 * the server is 1-based. Nothing here depends on the base -- the ranks are only
 * ever compared to each other -- but the two now agree, which they did not. */
import type { Urgency } from "./urgency.gen";

export { URGENCY, URGENCY_RANK } from "./urgency.gen";
export type { Urgency };

export type QueueStatus =
  | "WAITING" | "IN_PROGRESS" | "COMPLETED" | "CANCELLED";

export interface Patient {
  id: number;
  name: string;
  phone: string | null;
}

export interface Doctor {
  id: number;
  name: string;
  is_on_duty?: boolean;
}

export interface TriageResult {
  triage_id: number;
  patient_id: number;
  patient_name: string;
  urgency_level: Urgency;
  possible_conditions: string | null;
  /** Softmax maximum. NOT a calibrated probability -- the model was never
   *  calibrated. The UI must never render this as a percentage confidence. */
  confidence_score: number | null;
  ai_response_rw: string | null;
  /** Speaker-authored text, or null. Never machine-drafted. */
  patient_response: string | null;
  /** True when no speaker has authored a response for this language. */
  response_pending: boolean;
  response_pending_reason: string | null;
  language_detected: string | null;
  /** The queue entry's primary key, for addressing /queue/{id}/... */
  queue_id: number;
  queue_number: number;
  queue_position: number;
  estimated_wait: number | null;
  created_at: string;
}

export interface QueueEntry {
  id: number;
  queue_number: number;
  urgency_level: Urgency;
  status: QueueStatus;
  patient_id?: number;
  patient_name?: string | null;
  doctor_name?: string | null;
  estimated_wait: number | null;
}

export interface LoginResponse {
  access_token?: string;
  token?: string;
}

/** The API returns either a bare array or a paginated envelope depending on
 *  the endpoint. Normalising here keeps that inconsistency out of components. */
export function toList<T>(body: unknown): T[] {
  if (Array.isArray(body)) return body as T[];
  if (body && typeof body === "object" && "items" in body) {
    const items = (body as { items: unknown }).items;
    if (Array.isArray(items)) return items as T[];
  }
  return [];
}
