"""add updated_at to append-only tables

Revision ID: bbb8e77ab79d
Revises: ca53d84340e4
Create Date: 2026-08-31 08:45:11.878802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbb8e77ab79d'
down_revision: Union[str, Sequence[str], None] = 'ca53d84340e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sms_logs', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('symptom_reports', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('triage_results', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('triage_results', 'updated_at')
    op.drop_column('symptom_reports', 'updated_at')
    op.drop_column('sms_logs', 'updated_at')
    # ### end Alembic commands ###
