"""The frontend's urgency ordering still matches the enum it was generated from.

AUDIT 1.3. The ordering had five copies; the frontend's was one of them, and
it was hand-written. It is now generated by
`scripts/gen_frontend_constants.py` from `UrgencyLevel._URGENCY_PRIORITY`.

Generation alone does not prevent drift -- it only moves the drift to "someone
changed the enum and did not regenerate". This test is what closes that, and it
runs in the backend CI job, which is the job that fails when the enum changes.
It is deliberately here rather than in the frontend suite: the frontend cannot
read Python, and the thing being protected is the Python definition.
"""

from __future__ import annotations

import sys
from pathlib import Path

import pytest

BACKEND = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(BACKEND))

from scripts.gen_frontend_constants import OUT, render  # noqa: E402


def test_the_generated_file_exists() -> None:
    assert OUT.exists(), (
        f"{OUT} is missing. Generate it:\n"
        "  cd kinyamed/backend && python scripts/gen_frontend_constants.py"
    )


def test_the_generated_file_matches_the_enum() -> None:
    """The whole point: change the enum, regenerate, or fail here."""
    assert OUT.read_text(encoding="utf-8") == render(), (
        f"{OUT.name} has drifted from UrgencyLevel. Regenerate it:\n"
        "  cd kinyamed/backend && python scripts/gen_frontend_constants.py"
    )


def test_the_ordering_is_the_one_the_queue_sorts_by() -> None:
    """Guard the direction, not just the agreement.

    Two files can agree and both be wrong. CRITICAL sorting last would be a
    green parity test and a dead patient, so the clinical direction is asserted
    against the enum itself rather than against the generated text.
    """
    from app.models.triage_result import UrgencyLevel

    ordered = sorted(UrgencyLevel, key=lambda level: level.priority)
    assert [level.value for level in ordered] == ["CRITICAL", "URGENT", "ROUTINE"]


@pytest.mark.parametrize("name", ["CRITICAL", "URGENT", "ROUTINE"])
def test_every_level_reaches_the_frontend(name: str) -> None:
    """A level missing from the generated file sorts as `?? 9` in the client.

    `hooks.ts` falls back to 9 for an unknown urgency, so a level that never
    reached the frontend would be sorted LAST rather than raising -- silent,
    and wrong in the dangerous direction if the missing one is CRITICAL.
    """
    assert f"  {name}: " in OUT.read_text(encoding="utf-8")


# ── Queue bands (item 2d) ────────────────────────────────────────────────────
# The board groups rows into bands, and the header text a clinician reads is the
# backend's label. Both cross the language boundary, so both are generated.


def test_the_band_file_matches_queue_band() -> None:
    from scripts.gen_frontend_constants import BAND_OUT, render_bands

    assert BAND_OUT.exists(), "queueBand.gen.ts is missing; run the generator"
    assert BAND_OUT.read_text(encoding="utf-8") == render_bands(), (
        f"{BAND_OUT.name} has drifted from QueueBand. Regenerate it:\n"
        "  cd kinyamed/backend && python scripts/gen_frontend_constants.py"
    )


def test_the_band_order_puts_needs_review_second() -> None:
    """Direction, not agreement: asserted against the enum itself."""
    from app.models.queue_band import QueueBand

    ordered = sorted(QueueBand, key=int)
    assert [band.name for band in ordered] == [
        "CRITICAL",
        "NEEDS_REVIEW",
        "URGENT",
        "ROUTINE",
    ]


def test_the_review_label_reaches_the_frontend_verbatim() -> None:
    from scripts.gen_frontend_constants import BAND_OUT

    assert (
        '  NEEDS_REVIEW: "Model could not classify — review these first",'
        in BAND_OUT.read_text(encoding="utf-8")
    )
